- name: "installing tabular so lib"
  shell: |
    cd /usr/lib/x86_64-linux-gnu/rados-classes/ ;
    sudo cp {{ so_path }} . ;
    sudo ln -s libcls_tabular.so.1.0.0 libcls_tabular.so.1 ;
    sudo ln -s libcls_tabular.so.1 libcls_tabular.so ;
  ignore_errors: yes
